main:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
  - identifier: "posts"
    name: "Posts"
    url: "/posts"
    weight: 2
  - identifier: "about"
    name: "About me"
    url: "/about"
    weight: 3
  - identifier: "resume"
    name: "Resume"
    url: "/resume.pdf"
    weight: 4

# Social Media Configuration
social:
  - identifier: "linkedin"
    name: "Linkedin"
    url: "https://linkedin.ch-naseem.com/"
    weight: 1
  - identifier: "github"
    name: "GitHub"
    url: "https://github.ch-naseem.com/"
    weight: 2
  - identifier: "fediverse"
    name: "Fediverse"
    url: "https://social.ch-naseem.com/ndpm13"
    weight: 3
